language: cpp

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:allegro/5.2
  && echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
  && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  && sudo apt-get -qq update
  && sudo apt-get install -y liballegro5-dev libpugixml-dev i686-w64-mingw32.static-pugixml i686-w64-mingw32.static-jpeg i686-w64-mingw32.static-libpng i686-w64-mingw32.static-zlib i686-w64-mingw32.static-vorbis i686-w64-mingw32.static-opus i686-w64-mingw32.static-physfs i686-w64-mingw32.static-libwebp
  && mkdir liballeg_w32
  && cd liballeg_w32
  && git clone https://github.com/liballeg/allegro5.git
  && cd allegro5
  && cmake -DSHARED=0 -DWANT_DEMO=0 -DWANT_EXAMPLES=0 -DCMAKE_TOOLCHAIN_FILE=/usr/lib/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake
  && make
  && cd ../..
  && export PATH=$PATH:/usr/lib/mxe/usr/bin ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install --HEAD allegro ; fi

compiler: clang

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && make clean && make -f makefile.travis_mingw ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
