
language: cpp

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:allegro/5.2 && sudo apt-get -qq update && sudo apt-get install -y liballegro5-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install --HEAD allegro ; fi
  
compiler: clang

script: make
