language: cpp

os:
- linux
- osx

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:allegro/5.2
  && sudo add-apt-repository -y ppa:anton+/miscellaneous
  && sudo apt-get -qq update
  && sudo apt-get install -y liballegro5-dev libpugixml-dev libsamplerate-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install --HEAD allegro && brew install pugixml && brew install libsamplerate; fi

compiler: clang

script:
- cmake . -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++
- make
